using Postgrest.Models;
using Postgrest.Attributes;
using System.Text.Json.Serialization;

namespace BlogSpace.Client.Models
{
    [Table("posts")]
    public class Post : BaseModel
    {
        [Column("id")]
        public string? Id { get; set; } // uuid, generated by db or client

        [Column("title")]
        public string Title { get; set; } = string.Empty;

        [Column("content")]
        public string Content { get; set; } = string.Empty;

        [Column("summary")]
        public string? Summary { get; set; }

        [Column("visibility")]
        public string Visibility { get; set; } = "public";

        [Column("author_id")]
        public string AuthorId { get; set; } = string.Empty; // uuid

        [Column("created_at")]
        public DateTime CreatedAt { get; set; }

        [Column("updated_at")]
        public DateTime UpdatedAt { get; set; }

        [Column("published")]
        public bool Published { get; set; }

        [Column("tags")]
        public List<string> Tags { get; set; } = new(); // text[]

        [Column("slug")]
        public string Slug { get; set; } = string.Empty; // unique
    }
} 